trigger:
  branches:
    include:
      - master
  paths:
    include:
      - microservices/chat-query/*    

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3d1ad0db-d599-4435-9adb-6a8b384ee6b9'
  imageRepository: 'devopsfinal-chatquery'
  containerRegistry: 'acrdevopsfinal.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/microservices/chat-query/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'SELF_HOSTED_AGENT'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Push
  displayName: Push Stage
  dependsOn: Build
  jobs:
  - job: Push
    displayName: Push Job
    steps:
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

# - stage: Deploy
#   displayName: Deploy to K8S Stage
#   dependsOn: Push
#   jobs:
#   - job: Deploy
#     displayName: Deploy Job
#     steps:
#     - task: KubectlInstaller@0
#       inputs:
#         kubectlVersion: 'latest'

#     - script: |
#         kubectl create namespace chat-query || echo "Namespace 'chat-query' already exists"
#       displayName: 'Create Namespace'

#     - task: KubernetesManifest@1
#       inputs:
#         action: 'deploy'
#         connectionType: 'azureResourceManager'
#         azureSubscriptionConnection: 'npstackro-1676008966783(c50d4946-8f7f-487c-bc15-fcc1096ec82e)'
#         azureResourceGroup: 'devops-final-rg'
#         kubernetesCluster: 'mydemokubercicd'
#         namespace: 'chat-query'
#         manifests: '$(Build.SourcesDirectory)/microservices/k8s-specifications/chat-query/*.yml'  # Ensure this path matches where your .yml files are stored
#         containers: 'devopsfinal_images'
#         imagePullSecrets: '+PRm4ueVbmR2L98ygDODbhSlg2dskDDww/jCoVt4re+ACRCK2g0D'  # Add this if your cluster requires image pull secrets
