# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
#   paths:
#     include:
#       - microservices/chat-operation/*

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - microservices/chat-operation/*     


resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3d1ad0db-d599-4435-9adb-6a8b384ee6b9'
  imageRepository: 'devopsfinal-chatoperation'
  containerRegistry: 'acrdevopsfinal.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/microservices/chat-operation/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
 name: 'SELF_HOSTED_AGENT'




stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: Push
  displayName: Push Stage
  dependsOn: Build
  jobs:
  - job: Push
    displayName: Push Job
    steps:
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
