apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-nginx
  ports:
  - protocol: TCP
    port: 80            # The port that will be exposed externally
    targetPort: 8080     # The port on the container that the traffic should be routed to
  type: LoadBalancer
