apiVersion: v1
kind: Service
metadata:
  name: chat-operation-service
  labels:
    app: chat-operation
spec:
  selector:
    app: chat-operation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  # type: ClusterIP
  type: LoadBalancer

